AUTO_CREATE = True

NAME_SEPARATOR = "_"

NAME_PREFIX = "branch"

NAME_SUFFIX = ""

NAME_SCHEME = "{prefix}{separator}{branch}{suffix}"

DEFAULT_DATABASE_NAME = None

DATABASE_TEMPLATE = DEFAULT_DATABASE_NAME
